<div class="clearfix">
    <h1 id="logo">
        Gestió de Categories
    </h1>
</div><br>
<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <div class="row">
            <div class="col col-xs-6">
                <h3 class="panel-title">Categories</h3>
            </div>
            <div class="col col-xs-6 text-right">
                <a href="<?= $this->url('admin-categories', ['action' => 'add']) ?>" type="button" class="btn btn-sm btn-primary btn-create">Nova categoria</a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-bordered table-list">
            <thead>
                <tr>
                    <th>Nom</th>
                    
                    <th  style="width:100px; text-align: center;"><em class="fa fa-cog"></em></th>
                </tr> 
            </thead>
            <tbody>
                
                <?php foreach ($categories as $categoria) { ?>
      
                    <tr>
                        <td><?php echo utf8_encode($categoria->name); ?></td>
                        <td align="center">
                            <a href="<?= $this->url('admin-categories', ['action' => 'update', 'id' => $categoria->id]); ?>" class="btn btn-warning"><em class="fa fa-pencil"></em></a>
                            <button data-id="<?= $categoria->id ?>" data-controller="admin-categories" class="btn btn-danger delete"><em class="fa fa-trash"></em></button>
                        </td>
                    </tr>
                <?php } ?>  
            </tbody>
        </table>

    </div>

</div>



