<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <?php
        $username=$form->get('username');
        $username->setAttribute('class', 'form-control');
        $username->setAttribute('placeholder', 'e-mail');
        
        $password=$form->get('password');
        $password->setAttribute('class', 'form-control');
        $password->setAttribute('placeholder', 'contrasenya');
        
        $submit=$form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');
        
        $form->setAttribute('action', $this->url('index'));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
            <div class="form-group">
                <?= $this->formLabel($username) ?>
                <?= $this->formElement($username) ?>
                <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($password) ?>
                <?= $this->formElement($password) ?>
                <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
            </div>
            <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-xs-offset-3">
            <?= $this->formSubmit($submit);?>
            
            </div>
            <?php
            echo $this->form()->closeTag();
            ?>
        </div>    
    </div>      
</div>
