<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <p><?= $messageLogin; ?></p>
            <div class="form">
            <form action="<?= $this->url('index') ?>" method="POST" >
                <fieldset>
                    <legend>Entra!</legend>
                    <input type="hidden" name="form" value="formLogin">
                    <div class="form-group">
                        <label for="email">E-mail</label>
                        <input type="email" name="email" class="form-control" placeholder="e-mail" requierd>
                    </div>
                    <div class="form-group">
                        <label for="password">Contrasenya</label>
                        <input type="password" name="password" class="form-control" placeholder="Contrasenya" min="8" required>
                    </div>
                    <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-xs-offset-3">
                        <input type="submit" value="LogIn" class="btn btn-primary">

                    </div>
                </fieldset>
            </form>
            </div>
        </div> 
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <p><?= $messageRegister; ?></p>
             <div class="form">
            <form action="<?= $this->url('index') ?>" method="POST">
                <fieldset>
                    <legend>Registra't!</legend>
                    <input type="hidden" name="form" value="formRegitrar">
                    <div class="form-group">
                        <label for="email">E-mail</label>
                        <input type="email" name="email" class="form-control" placeholder="e-mail" requierd>
                    </div>
                    <div class="form-group">
                        <label for="password">Contrasenya</label>
                        <input type="password" name="password" class="form-control" placeholder="Contrasenya" min="8" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Nom</label>
                        <input type="text" name="name" class="form-control" placeholder="Nom" required>
                    </div>
                    <div class="form-group">
                        <label for="surname">Cognom</label>
                        <input type="text" name="surname" class="form-control" placeholder="Cognom" required>
                    </div>
                    <div class="form-group">
                        <label for="rol_id">Tipus d'usuari</label>
                        <select name="rol_id" class="form-control">
                            <?php foreach ($this->rols as $rol) {?>
                            <option value="<?php echo $rol->id; ?>"><?php echo $rol->name; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-xs-offset-3">
                        <input type="submit" value="LogIn" class="btn btn-primary">

                    </div>
                </fieldset>
            </form>
             </div>
        </div>
    </div>
</div>
