<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            
            <form action="<?=$this->url('index')?>" method="POST">
                <fieldset>
                    <legend>Login</legend>
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="email" name="email" class="form-control" placeholder="e-mail" requierd>
            </div>
            <div class="form-group">
               <label for="password">Contrasenya</label>
               <input type="password" name="password" class="form-control" placeholder="Contrasenya" min="8" required>
            </div>
            <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-xs-offset-3">
                <input type="submit" value="LogIn" class="btn btn-primary">
            
            </div>
                </fieldset>
            </form>
        </div>    
    </div>      
</div>
