<?php
session_start();
$rss = new DOMDocument();
$rss->load('https://as.com/rss/tags/ultimas_noticias.xml');

$feed = array();

foreach ($rss->getElementsByTagName('item') as $node) {
    $items = array(
        'title' => $node->getElementsByTagName('title')->item(0)->nodeValue,
        'desc' => $node->getElementsByTagName('description')->item(0)->nodeValue,
        'link' => $node->getElementsByTagName('link')->item(0)->nodeValue,
        'date' => $node->getElementsByTagName('pubDate')->item(0)->nodeValue,
    );

    $feed[] = $items;
}
?>
<div class="container">
<?php
$limit = 15;

for ($i = 0; $i < $limit; $i++) {
    if (isset($feed[$i]['title'])) {
        $item = $i + 1;
        $title = $feed[$i]['title'];
        $link = $feed[$i]['link'];
        $description = $feed[$i]['desc'];
        $date = date('d/M/Y H:i', strtotime($feed[$i]['date']));
        ?>  
        <div class="col-md-12 col-sm-12">
            <div class="panel panel-success cos">  
                <div class="capsal"><h3><a href="<?=$link?>"><?=$title?></a></h3></div>
                <div class="noticia" >
                    <p><?=$description?></p>
                    <p><?=$date?></p>                  
                </div>
            </div>
        </div>
 
  
    <?php }
    }
    ?>

</div>