<div class="clearfix">
    <h1 id="logo">
        Modificar competició
    </h1>
</div><br>
<?php
// This provides a default CSS class and placeholder text for the title element:
// This provides a default CSS class and placeholder text for the artist element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nom');

$cat_competicio=$form->get('cat_competicio');
$cat_competicio->setAttribute('class', 'form-control');
// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');?>
<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
<?php
$form->setAttribute('action', $this->url('admin-competicions', ['action' => 'update', 'id'=>$id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($cat_competicio) ?>
    <?= $this->formNumber($cat_competicio) ?>
    <?= $this->formElementErrors()->render($cat_competicio, ['class' => 'help-block']) ?>
</div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>

