<div class="clearfix">
    <h1 id="logo">
        Gestió d'usuaris
    </h1>
</div><br>
<div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">Usuaris</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                    <a href="<?= $this->url('admin-users', ['action' => 'add']) ?>" type="button" class="btn btn-sm btn-primary btn-create">Nou usuari</a>
                  </div>
                </div>
              </div>
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Cognom</th>
                        <th>Email</th>
                        <th>Rol</th>
                        <th  style="width:100px;"><em class="fa fa-cog"></em></th>
                    </tr> 
                  </thead>
                  <tbody>
                        <?php foreach ($users as $user){ ?>
                          <tr>
                            <td><?php echo "1"; ?></td>
                            <td class="hidden-xs">1</td>
                            <td>John Doe</td>
                            <td>johndoe@example.com</td>
                            <td align="center">
                              <a class="btn btn-warning"><em class="fa fa-pencil"></em></a>
                              <a class="btn btn-danger"><em class="fa fa-trash"></em></a>
                            </td>
                          </tr>
                        <?php } ?>  
                        </tbody>
                </table>
            
              </div>
              <div class="panel-footer">
                <div class="row">
                  <div class="col col-xs-4">Page 1 of 5
                  </div>
                  <div class="col col-xs-8">
                    <ul class="pagination hidden-xs pull-right">
                      <li><a href="#">1</a></li>
                      <li><a href="#">2</a></li>
                      <li><a href="#">3</a></li>
                      <li><a href="#">4</a></li>
                      <li><a href="#">5</a></li>
                    </ul>
                    <ul class="pagination visible-xs pull-right">
                        <li><a href="#">«</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>


<?php foreach ($users as $user){ ?>
<pre><?php print_r($user); ?></pre>
<?php } ?>
