<div class="clearfix">
    <h1 id="logo">
        Agregar nou usuari
    </h1>
</div><br>


<?php
// This provides a default CSS class and placeholder text for the title element:
$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'E-mail');

// This provides a default CSS class and placeholder text for the artist element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Nom');

$surname = $form->get('surname');
$surname->setAttribute('class', 'form-control');
$surname->setAttribute('placeholder', 'Cognom');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Contrasenya');



$rol_id = $form->get('rol_id');
$rol_id->setAttribute('class', 'form-control');


// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');?>
<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
<?php
$form->setAttribute('action', $this->url('admin-users', ['action' => 'update', 'id'=>$id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($username) ?>
    <?= $this->formElement($username) ?>
    <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($surname) ?>
    <?= $this->formElement($surname) ?>
    <?= $this->formElementErrors()->render($surname, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($rol_id) ?>
    <?= $this->formElement($rol_id) ?>
    <?= $this->formElementErrors()->render($rol_id, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>
