<!DOCTYPE HTML>
<!--
	Aesthetic by gettemplates.co
	Twitter: http://twitter.com/gettemplateco
	URL: http://gettemplates.co
-->

<html>
	<head>
            <title>Futur Sport</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- Estil personal -->
            <link href="<?php echo $this->basePath(); ?>/css/estils.css" rel="stylesheet" type="text/css" media="screen">


            <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            
            
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <!-- jQuery library -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                    <script src="<?php echo $this->basePath(); ?>/custom.js"></script>

	</head>
	<body>
	<nav class="navbar navbar-inverse" id="capçal">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index">FuturSport</a>
            </div>
                <?php if(isset($_SESSION['usuariConectat'])){ ?>
            <div class="collapse navbar-collapse js-navbar-collapse">
                 <div class="col-sm-3 col-md-3 col-sx-12 ">
                    <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Busca per nom" name="search" id="search">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                    </form>
                     <div id="divBusqueda" class="col-lg-12 col-md-12  col-sm-12 col-sx-12">
                         <ul id="llistaBusqueda">
                             
                         </ul>
                     </div>
                </div>
                
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="<?= $this->url('index'); ?>">Camp</a></li>
                    <li><a href="<?= $this->url('profile', ['action'=>'profile', 'id'=>$_SESSION['usuariConectat']['id']]); ?>">Fitxa</a></li>
                    <li><a href="notices">Notices</a></li>

                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?= $_SESSION['usuariConectat']['name'].' '.$_SESSION['usuariConectat']['surname'];?> <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="<?=$this->url('index', ['action'=>'logout']); ?>">Sortir</a></li>
                      </ul>
                    </li>
                  </ul>
                <?php } ?>
            </div>
        </nav>  
	
	<div>
		<?= $this->content ?>
	</div>

	
	<!--<footer id="gtco-footer" class="col-xs-12 text-center">
            <p>&copy; 2015 - <?= date('Y') ?> by Marta Farré Llordés. All rights reserved.</p>
	</footer>-->
</html>