<!DOCTYPE HTML>
<!--
	Aesthetic by gettemplates.co
	Twitter: http://twitter.com/gettemplateco
	URL: http://gettemplates.co
-->
<html>
	<head>
            <title>Futur Sport</title>
	</head>
	<body>
		
	
	
	<div>
		<?= $this->content ?>
	</div>

	
	<!--<footer id="gtco-footer" class="col-xs-12 text-center">
            <p>&copy; 2015 - <?= date('Y') ?> by Marta Farré Llordés. All rights reserved.</p>
	</footer>-->
</html>