<!DOCTYPE HTML>
<!--
	Aesthetic by gettemplates.co
	Twitter: http://twitter.com/gettemplateco
	URL: http://gettemplates.co
-->
<html>
	<head>
            <title>Futur Sport</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- Estil personal -->
            <link href="<?php echo $this->basePath(); ?>/css/estils.css" rel="stylesheet" type="text/css" media="screen">


            <!-- Latest compiled and minified CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            
            <!-- jQuery library -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

            <!-- Latest compiled JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
                    <script src="<?php echo $this->basePath(); ?>/custom.js"></script>

	</head>
	<body>
	<nav class="navbar navbar-inverse ">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="index">FuturSport</a>
                </div>	
            </div>
        </nav>  
	
	<div>
		<?= $this->content ?>
	</div>

	
	<!--<footer id="gtco-footer" class="col-xs-12 text-center">
            <p>&copy; 2015 - <?= date('Y') ?> by Marta Farré Llordés. All rights reserved.</p>
	</footer>-->
</html>